const jobs = [
  {
    id: 1,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/amazon.svg",
    company: "Amazon",
    posted: "2 days ago",
    post: "Senior UI/UX Developer",
    tag: "Full Time",
    tag2: "Senior Level",
    salary: "$120/hr",
    location: "Bengaluru, India",
  },
  {
    id: 2,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/apple.svg",
    company: "Apple",
    posted: "1 day ago",
    post: "Frontend Developer",
    tag: "Full Time",
    tag2: "Junior Level",
    salary: "$95/hr",
    location: "Hyderabad, India",
  },
  {
    id: 3,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/google.svg",
    company: "Google",
    posted: "4 days ago",
    post: "React Developer",
    tag: "Full Time",
    tag2: "Senior Level",
    salary: "$110/hr",
    location: "Pune, India",
  },
  {
    id: 4,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/netflix.svg",
    company: "Netflix",
    posted: "3 days ago",
    post: "UI Engineer",
    tag: "Full Time",
    tag2: "Senior Level",
    salary: "$125/hr",
    location: "Mumbai, India",
  },
  {
    id: 5,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/microsoft.svg",
    company: "Microsoft",
    posted: "5 days ago",
    post: "Software Engineer",
    tag: "Full Time",
    tag2: "Junior Level",
    salary: "$90/hr",
    location: "Noida, India",
  },
  {
    id: 6,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/meta.svg",
    company: "Meta",
    posted: "2 days ago",
    post: "Frontend Engineer",
    tag: "Full Time",
    tag2: "Senior Level",
    salary: "$115/hr",
    location: "Gurugram, India",
  },
  {
    id: 7,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/ibm.svg",
    company: "IBM",
    posted: "6 days ago",
    post: "Cloud Developer",
    tag: "Full Time",
    tag2: "Junior Level",
    salary: "$85/hr",
    location: "Chennai, India",
  },
  {
    id: 8,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/adobe.svg",
    company: "Adobe",
    posted: "1 day ago",
    post: "UI Developer",
    tag: "Full Time",
    tag2: "Junior Level",
    salary: "$80/hr",
    location: "Kolkata, India",
  },
  {
    id: 9,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/oracle.svg",
    company: "Oracle",
    posted: "3 days ago",
    post: "Backend Developer",
    tag: "Full Time",
    tag2: "Senior Level",
    salary: "$100/hr",
    location: "Ahmedabad, India",
  },
  {
    id: 10,
    logo: "https://cdn.jsdelivr.net/npm/simple-icons/icons/salesforce.svg",
    company: "Salesforce",
    posted: "2 days ago",
    post: "Full Stack Developer",
    tag: "Full Time",
    tag2: "Junior Level",
    salary: "$88/hr",
    location: "Delhi, India",
  },
];

export default jobs;